$setglobal REGION luxor
$setglobal BIOPH on
$setglobal CONS off
$setglobal DATABASE on
$setglobal ORCHARD on
$setglobal LIVESTOCK_simplified off
$setglobal CROP on
$setglobal PMPCalib on
$setglobal BiophCalib on
$setglobal VALUECHAIN on
$setglobal DIONYSUS off
$setglobal ENERGY on
$setglobal FIXEDIRRIGATION on
$setglobal LINUX on
