$setglobal REGION siliana
$setglobal BIOPH on
$setglobal CONS on
$setglobal DATABASE on
$setglobal ORCHARD on
$setglobal LIVESTOCK_simplified on
$setglobal CROP on
$setglobal PMPCalib on
$setglobal BiophCalib on
$setglobal VALUECHAIN on
$setglobal DIONYSUS on
$setglobal ENERGY on
$setglobal FIXEDIRRIGATION on
$setglobal LINUX on
